version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "Europe/Berlin"
    assignees:
      - dbuettgen
    commit-message:
      prefix: chore
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "Europe/Berlin"
    assignees:
      - dbuettgen
    commit-message:
      prefix: chore
    labels:
      - dependencies
      - github-actions
    groups:
      actions:
        patterns:
          - "*"